name: Installer CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  docker:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Build Installer
        run: ./build.sh
      - name: Archive build result
        uses: actions/upload-artifact@v2
        with:
          name: installer
          path: build/nsis/*.exe